namespace ETLEngine.Interfaces
{
    /// <summary>
    /// Represents a reporter to report <seealso cref="EngineMetrics"/> generated by a single ETL pipeline run. See <seealso cref="Engine{TIn, TOut}"/>.
    /// </summary>
    /// <typeparam name="TData">Type of objects to be extracted</typeparam>
    public interface IMetricsReporter
    {
        void Report(EngineMetrics metrics);
    }
}
